//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemandSet()
        {
            this.DealSet = new HashSet<DealSet>();
        }
    
        public int Id { get; set; }
        public int IdAgent { get; set; }
        public int IdClient { get; set; }
        public string Type { get; set; }
        public string MinPrice { get; set; }
        public string MaxPrice { get; set; }
        public string MinArea { get; set; }
        public string MaxArea { get; set; }
        public string MinRooms { get; set; }
        public string MaxRooms { get; set; }
        public string MinFloor { get; set; }
        public string MaxFloor { get; set; }
        public string MinFloors { get; set; }
        public string MaxFloors { get; set; }
    
        public virtual AgentsSet AgentsSet { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealSet> DealSet { get; set; }
    }
}
